spring:
  datasource:
    url: jdbc:postgresql://dpg-cmq1sl21hbls73fgvf60-a.oregon-postgres.render.com:5432/distribuida_a0ex
    username: distribuida_a0ex_user
    password: ohqVgg1A6M2aLOZp9BmUlSLS5z6NAEj9

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
server:
  port: 9090
