spring:
  datasource:
    url: jdbc:postgresql://dpg-cmptvb6g1b2c73fe2qh0-a.oregon-postgres.render.com/distribuida_0gjr
    username: distribuida_0gjr_user
    password: PBTnA2cr7y9KbdqSCRoiYyKuvI3dkuyz

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

app:
  authors:
    url: ${api.authors.url}
