server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoilBetrox/grupal-distribuida.git
          search-paths: config-data
        bootstrap: true
