server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/dennisyaj/dns-distribuida.git
          search-paths: config-data
